### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by affektde** [beyondcode/laravel-comments#13]
It would be very nice to use the package with Laravel 7.

**Comment by makroxyz** [comment]
Could you tag latest master branch with laravel 7 support please?

**Comment by dgillier** [comment]
Laravel 7 pls :))))

**Comment by nagi1** [comment]
Great now I have to fork just to pump the version up :)

**Comment by rajendrap123** [comment]
Please lets have Laravel 7 support

**Comment by srigurubyo** [comment]
It would be great to have support for the latest Laravel (7.*)

**Comment by rajendrap123** [comment]
any update on this ? its been long.....

**Comment by salvationarinze** [comment]
+1

**Comment by Domenikus** [comment]
+1

**Comment by 0x13ens** [comment]
+1

**Comment by jobyh** [comment]
As @makroxyz requests there just hasn't been a release tag since 7 support looks like it was added. I've added a comment in case anyone needs to work around this https://github.com/beyondcode/laravel-comments/issues/16#issuecomment-683413462
