### ISSUE TITLE
update package in packagist

### ISSUE THREAD

**Issue by alphaolomi** [beyondcode/laravel-comments#16]
the package on packagist is not updated 

Still there is not support for laravel 7

**Comment by LukeMadhanga** [comment]
+1

**Comment by jobyh** [comment]
Hi @alphaolomi @LukeMadhanga I just got snagged on this too. Looks like #14 added support for Laravel 7 some time ago. The reason it's not showing up on Packagist is that there hasn't been a corresponding release tag added. It looks like this is just an oversight.

Until this happens it is possible to install with 7 by telling composer to use the master branch:
`composer require beyondcode/laravel-comments:dev-master`
Not ideal but a workaround if you need the package.
