### ISSUE TITLE
Installation failure - PHP 8 not supported

### ISSUE THREAD

**Issue by MrThursby** [beyondcode/laravel-comments#23]
``` bash
$ composer require beyondcode/laravel-comments
[InvalidArgumentException]
Package beyondcode/laravel-comments has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version
```

**Comment by pro-cms** [comment]
HI @MrThursby  ,
first, the package is not updated for PHP 8, to get the latest updated version follow this instead
 https://github.com/Zepson-Technologies/laravel-comments and read an article about the package  https://zepson.co.tz/index.php/2020/12/31/laravel-comments-package/, ask any question from the repo or chatting area in the site

**Comment by rajendrap123** [comment]
I am getting this error

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ^7.2 but your PHP version (8.0.3) does not satisfy that requirement.
  Problem 2
    - beyondcode/laravel-comments 1.2.0 requires php ^7.2.5 -> your PHP version (8.0.3) does not satisfy that requirement.
    - beyondcode/laravel-comments 1.1.0 requires php ^7.2 -> your PHP version (8.0.3) does not satisfy that requirement.
    - beyondcode/laravel-comments 1.1.0 requires php ^7.2 -> your PHP version (8.0.3) does not satisfy that requirement.
    - Installation request for beyondcode/laravel-comments ^1.1 -> satisfiable by beyondcode/laravel-comments[1.1.0, 1.2.0].
