### ISSUE TITLE
Reply to comments

### ISSUE THREAD

**Issue by asivaneswaran** [beyondcode/laravel-comments#3]
Is it possible to reply to comments?

**Comment by piterjov** [comment]
> Is it possible to reply to comments?

Yes, just use  ` use HasComments;` trait on your Comment model like you do with regular commentable entities

**Comment by mreduar** [comment]
HasComments already comes by default added to the Comment model of the package

**Comment by snipiba** [comment]
for example...
if you will add comment to post, uses 
`
Post::first()->comentAsUser(...)
`
if you wish add reply to comment, uses
`
Comment::first()->commentAsUser(...)
`
