### ISSUE TITLE
Broken composer CDN version

### ISSUE THREAD

**Issue by DenisCJN** [beyondcode/laravel-comments#37]
https://satis.spatie.be/p2/spatie/laravel-comments.json

When I try and do a composer install, composer complains about a broken link (above)
![image](https://github.com/beyondcode/laravel-comments/assets/17960498/bfed6e32-3468-466f-8466-41c4ae57944d)
<img width="1236" alt="image" src="https://github.com/beyondcode/laravel-comments/assets/17960498/5c85eeac-5414-4203-ba2d-4af833c670fe">

**Comment by mpociot** [comment]
This repository isn't for the Spatie package, which seems to have the same name, sorry 😅
