### ISSUE TITLE
Delete Link Is Not Being Rendered Properly

### ISSUE THREAD

**Issue by FireOpsPhil** [beyondcode/laravel-comments#39]
I have the Laravel-comments component implemented throughout my project using something like this:

   <livewire:comments :model="$post"/>
   
   The delete link is being rendered as : comments::comments.destroy, instead of Delete.  Why?
   
   
![2024-04-09_17-49-48](https://github.com/beyondcode/laravel-comments/assets/145500847/d215c31f-4d9c-4f39-b16b-a3016fd5af49)

**Comment by philipsorensen** [comment]
I think this is an issue in your Livewire component rather than this package. Looks like a missing translation.
