### ISSUE TITLE
Extend comments model

### ISSUE THREAD

**Issue by dambridge** [beyondcode/laravel-comments#8]
I'd like to override your comments model with my own, so that I may add some additional data when creating comments, either through setters, etc. What is the best approach to doing this?

**Comment by Zontir** [comment]
I also have the same question. I would like to add a new trait to the comment model

**Comment by mreduar** [comment]
I did it this way

```
namespace App;

use BeyondCode\Comments\Comment as CommentSystem;
use Other\Trait\Name as NewTrait;

class Comment extends CommentSystem
{
    use NewTrait;
}
```
